trigger: none

pool:
  vmImage: ubuntu-latest

stages:

# Deploy to the test environment.
- template: pipeline-templates/deploy.yml
  parameters:
    testa: dev
    resourceGroupName: mytestrg
    serviceConnectionName: AzureSC

# Deploy to the production environment.
- template: pipeline-templates/deploy.yml
  parameters:
    testa: Production
    resourceGroupName: mytestrg
    serviceConnectionName: AzureSC
