trigger: none
 
pool:
  vmImage: ubuntu-latest
 
variables:
  ServiceConnectionName: 'MyServiceConnection'
  EnvironmentType: 'Test'
  ResourceGroupName: 'bicepsto'
 
jobs:
- job:
  steps:
  - task: AzureCLI@2
    inputs:
      azureSubscription: $(ServiceConnectionName)
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az deployment group create \
          --resource-group $(ResourceGroupName) \
          --template-file main.bicep \
          --parameters environmentType=$(EnvironmentType)