trigger: none

pool:
  vmImage: ubuntu-latest

variables:
  ServiceConnectionName: 'AzureSC'
  ResourceGroupName: 'mytestrg'

stages:

# Deploy to the test environment.
- template: pipeline-templates/deploy.yml
  parameters:
    testa: dev
    resourceGroupName: 'mytestrg'
    serviceConnectionName: $(ServiceConnectionName)

# Deploy to the production environment.
- template: pipeline-templates/deploy.yml
  parameters:
    testa: Production
    resourceGroupName: 'mytestrg'
    serviceConnectionName: $(ServiceConnectionName)
